steps:
  - name: 'terraform'
    args:
      - 'init'
    dir: '/'

  - name: 'terraform'
    args:
      - 'plan'
    dir: '/'

  - name: 'terraform'
    args:
      - 'apply'
      - '-auto-approve'
    dir: '/'


