steps:
  - id: 'tf init'
    name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args: 
      - '-c'
      - | 
          terraform init

  - id: 'tf destroy'
    name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args: 
      - '-c'
      - | 
          terraform destroy -auto-approve

  - id: 'tf plan'
    name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args: 
      - '-c'
      - | 
          terraform plan

  - id: 'tf apply'
    name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args: 
      - '-c'
      - |   
          terraform apply -auto-approve

